const REGISTER = {
  REGISTER_INITLIZATION: "REGISTER_INITLIZATION",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_ERORR: "REGISTER_ERORR",
};

const LOGIN = {
  LOGIN_INITLIZATION: "LOGIN_INITLIZATION",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERORR: "LOGIN_ERORR",
};
const LOGOUT = {
  LOGOUT_INITLIZATION: "LOGOUT_INITLIZATION",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_ERORR: "LOGOUT_ERORR",
};
const FORGOT_PASSWORD = {
  FORGOT_PASSWORD_INITLIZATION: "FORGOT_PASSWORD_INITLIZATION",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_ERORR: "FORGOT_PASSWORD_ERORR",
};
const VERIFY_OTP_ACTION = {
  VERIFY_OTP_ACTION_INITLIZATION: "VERIFY_OTP_ACTION_INITLIZATION",
  VERIFY_OTP_ACTION_SUCCESS: "VERIFY_OTP_ACTION_SUCCESS",
  VERIFY_OTP_ACTION_ERORR: "VERIFY_OTP_ACTION_ERORR",
};
export { REGISTER, LOGIN, FORGOT_PASSWORD, LOGOUT, VERIFY_OTP_ACTION };
